# Generated by Django 3.2.9 on 2021-11-23 16:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('studentScoreAverage', models.DecimalField(decimal_places=2, max_digits=7)),
                ('gender', models.BooleanField()),
                ('cutoff', models.DecimalField(decimal_places=2, max_digits=7)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentScore',
            fields=[
                ('averageScore', models.DecimalField(decimal_places=2, max_digits=7)),
                ('mathes', models.IntegerField(default=0)),
                ('English', models.IntegerField(default=0)),
                ('Kiswahili', models.IntegerField(default=0)),
                ('Science', models.IntegerField(default=0)),
                ('SocialStudies', models.IntegerField(default=0)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ApplicationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('cutoff', models.DecimalField(decimal_places=2, max_digits=7)),
                ('application', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.application')),
                ('school', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.school')),
            ],
        ),
    ]
