# Generated by Django 3.2.9 on 2021-11-24 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_school_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationitem',
            name='id',
        ),
        migrations.AddField(
            model_name='applicationitem',
            name='_id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='applicationitem',
            name='cutoff',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=7),
        ),
    ]
