# Generated by Django 3.2.9 on 2021-11-30 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_rename_students_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AddField(
            model_name='student',
            name='_id',
            field=models.AutoField(default=0, editable=False, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
