# Generated by Django 3.2.9 on 2021-12-05 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20211205_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentscore',
            old_name='English',
            new_name='english',
        ),
        migrations.RenameField(
            model_name='studentscore',
            old_name='Kiswahili',
            new_name='kiswahili',
        ),
        migrations.RenameField(
            model_name='studentscore',
            old_name='Science',
            new_name='science',
        ),
        migrations.RenameField(
            model_name='studentscore',
            old_name='SocialStudies',
            new_name='socialStudies',
        ),
    ]
