# Generated by Django 3.2.9 on 2021-12-05 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_auto_20211205_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='numberOfstudents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
