# Generated by Django 3.2.9 on 2021-12-05 07:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0012_alter_school_numberofstudents'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentScore',
            new_name='StudentScores',
        ),
    ]
