# Generated by Django 3.2.9 on 2021-12-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_rename_studentscore_studentscores'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='numberOfChoice',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
