# Generated by Django 3.2.9 on 2021-12-20 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_auto_20211216_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationitem',
            name='numberOfChoice',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='applicationitem',
            name='numberOfstudents',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
