# Generated by Django 3.2.9 on 2022-01-15 00:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_auto_20220115_0337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='student',
        ),
    ]
