# Generated by Django 3.2.9 on 2022-01-15 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_remove_application_student'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentscores',
            name='averageScore',
        ),
    ]
