# Generated by Django 3.2.9 on 2022-01-15 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_remove_studentscores_averagescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
