# Generated by Django 3.2.9 on 2022-01-15 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_applicationitem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='application',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.application'),
        ),
    ]
