# Generated by Django 3.2.9 on 2022-01-18 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_student_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='image',
            field=models.ImageField(blank=True, default='/placeholder.png', null=True, upload_to=''),
        ),
    ]
