# Generated by Django 3.2.9 on 2022-01-19 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20220119_1403'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationitem',
            name='student',
        ),
    ]
