# Generated by Django 3.2.9 on 2022-01-19 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_applicationitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationitem',
            name='user',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
