# Generated by Django 3.2.9 on 2022-01-20 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_alter_applicationitem_student'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applicationitem',
            old_name='user',
            new_name='username',
        ),
    ]
