# Generated by Django 3.2.9 on 2022-01-20 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_rename_user_applicationitem_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationitem',
            name='cutoff',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='applicationitem',
            name='studentScoreAverage',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
